### PR TITLE
CSS <style scope> to <style scoped>

### PR DESCRIPTION
**Pull request by ghost**
Thank you for the "Vue JS Crash Course 2021".  It helped me a lot to understand the basics. 
While watching and doing it along with your video, I found what it seems like to be a typo? 
I apologize if it's not.

```vue
/* Task.vue */
<style scoped>
...
</style>
```

### CODE REVIEW

**Comment by DevShaded** [comment]
Yes, it's a typo it should be `<style scoped>`

**Comment by kojoYeboah53i** [comment]
update

**Comment by kojoYeboah53i** [comment]
update

**Review by ghost — APPROVED** [review]

**Comment by kojoYeboah53i** [comment]
update

**Pull request closed without merging**
